server:
  port: 9090
  http:
    port: 9000
     
spring:
  profiles:
    active: local

#data source configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment?currentSchema=crnr_hcms
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL92Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
              
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        descriptor:
          sql:
            BasicBinder:  TRACE